[2023-11-01T20:39:08.071-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dbt_snowflake_dag.dbt_run manual__2023-11-02T03:39:04.857645+00:00 [queued]>
[2023-11-01T20:39:08.076-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dbt_snowflake_dag.dbt_run manual__2023-11-02T03:39:04.857645+00:00 [queued]>
[2023-11-01T20:39:08.076-0700] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-01T20:39:08.076-0700] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-01T20:39:08.076-0700] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-01T20:39:08.081-0700] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): dbt_run> on 2023-11-02 03:39:04.857645+00:00
[2023-11-01T20:39:08.083-0700] {standard_task_runner.py:55} INFO - Started process 1699 to run task
[2023-11-01T20:39:08.085-0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_dag', 'dbt_run', 'manual__2023-11-02T03:39:04.857645+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dbt_airflow_snowflake.py', '--cfg-path', '/var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T/tmp3zfery2g']
[2023-11-01T20:39:08.087-0700] {standard_task_runner.py:83} INFO - Job 78: Subtask dbt_run
[2023-11-01T20:39:08.126-0700] {task_command.py:388} INFO - Running <TaskInstance: dbt_snowflake_dag.dbt_run manual__2023-11-02T03:39:04.857645+00:00 [running]> on host anishs-air.lan
[2023-11-01T20:39:08.151-0700] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_snowflake_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-11-02T03:39:04.857645+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-02T03:39:04.857645+00:00
[2023-11-01T20:39:08.152-0700] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T
[2023-11-01T20:39:08.152-0700] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --profiles-dir /Users/anishmore/airflow/dbt/data_pipeline/profiles.yml --project-dir /Users/anishmore/airflow/dbt/data_pipeline']
[2023-11-01T20:39:08.157-0700] {subprocess.py:86} INFO - Output:
[2023-11-01T20:39:09.426-0700] {subprocess.py:93} INFO - [0m03:39:09  Running with dbt=1.6.7
[2023-11-01T20:39:09.428-0700] {subprocess.py:93} INFO - [0m03:39:09  Encountered an error:
[2023-11-01T20:39:09.428-0700] {subprocess.py:93} INFO - Runtime Error
[2023-11-01T20:39:09.428-0700] {subprocess.py:93} INFO -   dbt cannot run because no profile was specified for this dbt project.
[2023-11-01T20:39:09.428-0700] {subprocess.py:93} INFO -   To specify a profile for this project, add a line like the this to
[2023-11-01T20:39:09.428-0700] {subprocess.py:93} INFO -   your dbt_project.yml file:
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO - 
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO -   profile: [profile name]
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO - 
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO -   Here, [profile name] should be replaced with a profile name
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO -   defined in your profiles.yml file. You can find profiles.yml here:
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO - 
[2023-11-01T20:39:09.429-0700] {subprocess.py:93} INFO -   /Users/anishmore/.dbt/profiles.yml
[2023-11-01T20:39:09.430-0700] {subprocess.py:93} INFO - 
[2023-11-01T20:39:10.082-0700] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-01T20:39:10.086-0700] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-01T20:39:10.088-0700] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=dbt_snowflake_dag, task_id=dbt_run, execution_date=20231102T033904, start_date=20231102T033908, end_date=20231102T033910
[2023-11-01T20:39:10.095-0700] {standard_task_runner.py:100} ERROR - Failed to execute job 78 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1699)
[2023-11-01T20:39:10.099-0700] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-01T20:39:10.109-0700] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
