[2023-10-24T20:18:02.690-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_dag.transform_task manual__2023-10-25T03:17:55.811978+00:00 [queued]>
[2023-10-24T20:18:02.696-0700] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_dag.transform_task manual__2023-10-25T03:17:55.811978+00:00 [queued]>
[2023-10-24T20:18:02.696-0700] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-24T20:18:02.696-0700] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-24T20:18:02.696-0700] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-24T20:18:02.702-0700] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): transform_task> on 2023-10-25 03:17:55.811978+00:00
[2023-10-24T20:18:02.704-0700] {standard_task_runner.py:55} INFO - Started process 22254 to run task
[2023-10-24T20:18:02.708-0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'transform_task', 'manual__2023-10-25T03:17:55.811978+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/basic_etl_dag.py', '--cfg-path', '/var/folders/jh/g6c8fm7j3x148qd22mrgmrsw0000gn/T/tmpod0skdup']
[2023-10-24T20:18:02.711-0700] {standard_task_runner.py:83} INFO - Job 29: Subtask transform_task
[2023-10-24T20:18:02.731-0700] {task_command.py:388} INFO - Running <TaskInstance: etl_dag.transform_task manual__2023-10-25T03:17:55.811978+00:00 [running]> on host anishs-air.lan
[2023-10-24T20:18:02.746-0700] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-25T03:17:55.811978+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-25T03:17:55.811978+00:00
[2023-10-24T20:18:02.757-0700] {logging_mixin.py:137} WARNING - /Users/anishmore/airflow/dags/basic_etl_dag.py:22 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-10-24T20:18:02.759-0700] {python.py:177} INFO - Done. Returned value was: None
[2023-10-24T20:18:02.762-0700] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=transform_task, execution_date=20231025T031755, start_date=20231025T031802, end_date=20231025T031802
[2023-10-24T20:18:02.768-0700] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-10-24T20:18:02.775-0700] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
